### ISSUE TITLE
atop 추가하기

### ISSUE THREAD

**Issue by simnalamburt** [femiwiki/ami#1]
서버 부하가 갑자기 커지거나 하는 상황에서 atop이 미리 깔려있으면 정말 유용할것같다. 달리 저렴하게 쓸 수 있는 디테일한 모니터링 수단도 없고, atop에 서버에 주는 부하가 큰것같지도 않으니 계속 깔아서 잘 써보자.

지금은 임시로 각 서버들에 `sudo yum install 'https://www.atoptool.nl/download/atop-2.4.0-1.x86_64.rpm'`를 실행한 상태

Related with https://github.com/femiwiki/femiwiki/issues/64

**Comment by lens0021** [comment]
패커 [bootstrap.sh](https://github.com/femiwiki/mediawiki/blob/4d4a2b2806291ad74d56ca28d64e42042bfdfbad/ami/bootstrap.sh)에 추가하면 될까요??

**Comment by simnalamburt** [comment]
네

**Comment by lens0021** [comment]
https://github.com/femiwiki/ami/commit/53c8d1f35a483bc312318929bd987f694f38d534

~~AMI 새로 구워야 합니다\~~~

- `femiwiki-base 2019-11-01`
- `femiwiki-mediawiki`

그냥 쓰기 전에 굽기로 합니다~
