### ISSUE TITLE
AMI 생성과정 packer와 Github action으로 자동화

### ISSUE THREAD

**Issue by lens0021** [femiwiki/ami#3]
TBD

- [x] IAM 작성 &rarr; https://github.com/femiwiki/infra/issues/22
- [x] IAM에서 토큰 생성하여 이 리포에 secret으로 추가
- [ ] 깃헙 액션 작성 &rarr; https://github.com/femiwiki/ami/blob/issue-3/.github/workflows/main.yml
- [ ] 오래된 AMI는 어떻게 할지 정하기

### Activity
- Hyeon Kim added [this card ](https://trello.com/c/fFRZgr6e)to Backlog - Dec 22 at 8:52 PM

**Comment by lens0021** [comment]
- https://www.packer.io/docs/builders/amazon.html#specifying-amazon-credentials
- https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets

위 둘 참고하였는데 "Build 'amazon-ebs' errored: No valid credential sources found for AWS Builder. Please see https://www.packer.io/docs/builders/amazon.html#specifying-amazon-credentials for more information on providing credentials for the AWS Builder."으로 실패합니다

**Comment by simnalamburt** [comment]
앞으로 페미위키용 AMI를 만들지 않을 계획임. Closing
